### PR TITLE
add course 'mount_josiah_and_alamo_sea'

### PR DESCRIPTION
**Pull request by oldnapalm**
Course name: (Gravel) Mount Josiah and Alamo Sea
Distance: 17.2 km / 10.7 mi
Elevation: 141 m / 463 ft
Description: Eight shaped route around Mount Josiah and Alamo Sea

### CODE REVIEW

**Comment by murech** [comment]
@oldnapalm No problem, thanks! I will proceed and merge to master. I will update the readme and create a new release v0.13.0.

**Comment by oldnapalm** [comment]
@murech thanks!

The distance for this course is actually 16.7 km / 10.4 mi

Previous measurement was from a GPX from a ride using vpower bot at 1000 watts, maybe it was the cause of the extra meters. This one was actually riding. Distance climbed was correct.

**Comment by murech** [comment]
@oldnapalm thanks for the update. The elevation data in the readme is calculated based on a slopescale of 0.5. This is because Nestor defined this as a default slopescale. Which slopescale are you using?

**Comment by oldnapalm** [comment]
I'm using slopescale 0.5

How do you calculate it?

I just converted the FIT file to GPX using https://www.gpsvisualizer.com and cut the file with https://getadze.com (I rode more than one lap).

**Comment by murech** [comment]
@oldnapalm yep, slopescale of 0.5 is fine. I was asking because if slopescale is less than 0.5 then elevation is also less. BTW, release is created: https://github.com/gtbikev/courses/releases/tag/v0.13.0. Thanks again!

**Pull request merged**
