### PR TITLE
add course 'gravel_mount_josiah'

### PR DESCRIPTION
**Pull request by oldnapalm**
Course name: (Gravel) Mount Josiah
Distance: 8.7 km / 5.4 mi
Elevation: 90 m / 295 ft
Description: Lap around Mount Josiah CCW

### CODE REVIEW

**Comment by murech** [comment]
Hi @oldnapalm 
Thanks for contributing. Can you please add map editor file and provide the CC0 waiver? For more details see guidelines: https://github.com/gtbikev/courses#guidelines

Thanks!

**Comment by oldnapalm** [comment]
Hi @murech 

I didn't use map editor to create this course, I used [CoordRecorder](https://github.com/oldnapalm/CoordRecorder) instead. Is Map Editor file required? I can provide a CSV which can be used to preview the course in https://gtagmodding.com/maps/gta5/

I, Cassio Davi, hereby waive all copyright and related or neighboring rights together with all associated claims and causes of action with respect to this work to the extent possible under the law.

**Comment by murech** [comment]
Hi @oldnapalm
Thanks for the cc0 waiver. It would be great to have the map editor file. It would help others which are using the map editor files to build upon or help fixing problems.

**Comment by oldnapalm** [comment]
Sure, if you don't mind.

I didn't make this course using Map Editor, so I don't have the xml file.

**Pull request merged**
