### PR TITLE
Proposed fix for various courses

### PR DESCRIPTION
**Pull request by oldnapalm**
Uses unrouted waypoints.

### CODE REVIEW

**Comment by murech** [comment]
@oldnapalm: please let me know once you have completed the updates. I will then create a new course release.

**Comment by oldnapalm** [comment]
Hi @murech, I fix the courses when I ride them and find an issue or a lot of waypoints close to each other (meaning it's a troublesome section). If you know about any courses that need a rework, please let me know. I know the guys from FB group are working on new courses, for me you can wait until some new courses come out, then make a release with them and the fixes.

**Comment by oldnapalm** [comment]
There are 2 new routes out, one is this by Steven Gilbert https://drive.google.com/file/d/1Xw4wNArrch9-iN3AS2IqSfHIdqi8sz4K/view, the other one was made by SK Yeatts, I believe he tried to contact you directly. When you can, maybe it's a good time for a new release with the new courses and the fixes in this pull request.

**Comment by murech** [comment]
@oldnapalm: thanks for providing the fixes.

**Pull request merged**
