### PR TITLE
Update html-api.html - improve distance/elevation metadata accuracy

### PR DESCRIPTION
**Pull request by defiancecp**
As I've been adding route previews using .gpx or .fit files, one thing that allows is to add a little semi-automated validation of metadata accuracy.  So I built a quick routine that auto-captures distance and elevation data from GPX or FIT files used in route previews, and a quick query that compares that result to the associated route's metadata.  Full result set below.  Mostly the distances were right (I propose some small adjustments), but there were quite a few elevation corrections.

Most are just tweaks, but some have significant changes.  For validation on those I'm proposing significant changes to, here's a look at the processed fit/gpx file preview:

elevation fixes:
https://gtbikevroutes.fun/default.php?met=Metric&route=gravel_windy_hills - major change: elevation metadata shows 494m, but this is showing 165m.
https://gtbikevroutes.fun/default.php?met=Metric&route=gravel_senora_desert - major change: metadata shows over 250m, but ride was more like 50m
https://gtbikevroutes.fun/default.php?met=Metric&route=gravel_grapeseed - major change: metadata shows over 150m, but ride was more like 45m
https://gtbikevroutes.fun/default.php?met=Metric&route=gravel_burro_heights - moderate change: metadata shows about 140m, but ride was more just under 100m

The only major distance change was to the tourist- https://gtbikevroutes.fun/default.php?met=Metric&route=the_tourist -- was overreporting distance by nearly a mile

The rest are fairly small adjustments.

And here's the full dataset:

RouteName	DistDeviation	ElevDeviation	LastSubmission	ReportedDistanceKM	GPXDistanceKM	GPXDistanceKM_StdDeviation	ReportedElevationM	GPXElevationM	GPXElevationM_StdDeviation
gravel_windy_hills	0.18	324.8	7/10/2020 6:09	9.6	9.78	0	490	165.2	0
gravel_senora_desert	0.05	199	7/10/2020 3:08	8	7.95	0	252	53	0
gravel_grapeseed	0.05	111.6	7/10/2020 17:22	4.5	4.55	0	156	44.4	0
gravel_el_burro_heights	0.26	52.4	7/10/2020 16:49	4.7	4.96	0	144	91.6	0
bmx_richman_golf	0.02	45	7/10/2020 16:41	1.3	1.32	0	62	17	0
the_tourist	0.72	34	7/9/2020 13:31	16.7	15.98	0	311	345	0
bmx_redwood_lights	0.04	30	7/10/2020 16:39	1.8	1.84	0	62	32	0
mtb_mount_chilliad	0.53	27.8	7/10/2020 16:50	10	9.47	0	278	250.2	0
road_land_act_dam_loop	0.05	17.6	7/9/2020 13:53	5	4.95	0	116	98.4	0
road_vinewood_heights	0.15	8.6	7/9/2020 13:31	8.2	8.05	0	193	201.6	0
gravel_davis_quartz	0.02	7.8	7/10/2020 16:42	3.8	3.78	0	66	73.8	0
Suburb_Crit	0	3.6	7/10/2020 16:48	1.4	1.4	0	10	6.4	0
los_santos_hills	0.01	0.4	7/10/2020 15:51	14	14.01	0	206	206.4	0
tour_los_santos	0.04	0.4	7/10/2020 16:47	30.1	30.06	0	533	533.4	0
gravel_mount_josiah_and_alamo_sea	0.06	0.2	7/10/2020 16:43	16.7	16.64	0	141	141.2	0
Palomino_Highlands	0	0.2	7/9/2020 20:46	7	7	0	124	123.8	0
alamo_sea	0	0.2	7/10/2020 16:38	9.9	9.9	0	70	70.2	0

### CODE REVIEW

**Comment by murech** [comment]
@defiancecp thanks for testing. Have you tested the courses with a slopescale of 0.5? What was your testing setup?

For example: 

**My Test Setup**
````
Wahoo Kickr Core, 2018
Mods: GT Bike V (0.3.0.2), Map Editor (2.13)
SLOPESCALE = 0.5 FECDEVICEID = 0 IMPERIAL = False > USERWEIGHTKG = 75
Import: Fit file upload to Strava
````

I'm asking because Nestor mentioned that using less slopescale would impact elevation. Once I know your setup, I could also test with my setup and compare to see if a different setup is impacting elevation. Moreover, this would help also to get some basic understanding about what would be a reference.

**Comment by defiancecp** [comment]
All slopescales are 0.5, and using default lat/long mapping.  
I used two different configs for testing on these:
* - Windy Hills: Tested riding myself, using Wahoo Kickr and Climb, but taking power from Quarq crank power meter (for some reason my kickr power results are overstated when my cadence is <50, and I like climbing really tough climbs so I stick with the PM).  For this one I had converted to .gpx, but otherwise just the normal file.
* - the other 3, I simulated them using SimulAnt+, running a static 240w / 60cadence simulated power meter.  For these I'm using the .fit file directly from GTBV mod.

Honestly, I kinda think the old numbers might've been just typos?  Windy hills for example, it's <10km -- Getting almost 500m of climbing and another 500 descent would be pretty impressive :)

**Comment by murech** [comment]
You are right, your provided metadata makes much more sense. Thanks for testing. I will check on my side why the elevation is that much off. I will overtake the metadata to the readme.

**Comment by oldnapalm** [comment]
> I will check on my side why the elevation is that much off.

If you got GPX from Strava it's probably the cause.

**Pull request merged**
