### PR TITLE
Adding courses

### PR DESCRIPTION
**Pull request by defiancecp**
Adding courses - no update to meta or descriptions

### CODE REVIEW

**Comment by defiancecp** [comment]
Adding my completed courses

**Comment by murech** [comment]
Hi @defiancecp. Thanks for the pull request. Can you please do the following things:
* use lower case for all file names
* provide map editor files (*.xml) - this helps if someone wants to contribute
* confirm with the following sentence that you waive all rights:  _I, {your name} hereby waive all copyright and related or neighboring rights together with all associated claims and causes of action with respect to this work to the extent possible under the law._ You find more information about CC0 license here: https://creativecommons.org/share-your-work/public-domain/cc0/

Thanks again!

**Comment by defiancecp** [comment]
I, Richard Slaughter hereby waive all copyright and related or neighboring rights together with all associated claims and causes of action with respect to this work to the extent possible under the law.

**Comment by defiancecp** [comment]
Original map builder files aren't available any longer, just never saved them - but I can make xml files with the coordinates encoded in the same format as the map builder files, hopefully that will suffice.  Will update shortly.

**Pull request merged**
